chore(seer): Update packages and fix typing (#2587)
- Update packages
- Specifically google-genai so that thinking features on the 2.5 models
can be adjusted
- Fix typing in `clients.py` 
- Update a few relevant tests

**Note:** Ignoring some typing because of issues like the following: 

``` python
src/seer/automation/agent/client.py:1047: error: Argument "contents" to "generate_content_stream" of "Models" has incompatible type "list[Content]"; expected "list[Content | list[File | Part | Image | str] | File | Part | Image | str] | Content | list[File | Part | Image | str] | File | Part | Image | str | list[Content | list[File | Part | Image | str] | File | Part | Image | str | ContentDict] | Content | list[File | Part | Image | str] | File | Part | Image | str | ContentDict"  [arg-type]
```

As we can see, the type is indeed correct, but the type checker isn't
properly picking it up